url: http://egonzalez.org
title: OpenStack things
email: dabarren@gmail.com
description: OpenStack, Docker, Ansible, Ceph, Linux
twitter_username: egongu90
github_username:  egonzalez90

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
